name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'wizardsdata/**'
      - 'docs/**'
      - '.github/workflows/docs.yml'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints
    
    - name: Build documentation
      run: |
        cd docs
        make html SPHINXOPTS="-W"
    
    - name: Prepare docs directory for GitHub Pages
      run: |
        # Clean docs directory (preserving source and build)
        find docs -mindepth 1 -maxdepth 1 -not -name "source" -not -name "build" -not -name "Makefile" -not -name "make.bat" -exec rm -rf {} \;
        
        # Copy built HTML files directly to docs directory
        cp -r docs/build/html/* docs/
        
        # Create .nojekyll file to prevent Jekyll processing
        touch docs/.nojekyll
    
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs
        git commit -m "Update documentation" || echo "No changes to commit"
        git push